spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/championdo?useSSL=false
    #    url: jdbc:mysql://node34473-dusheff.es-1.axarnet.cloud:3306/damian
    username: root
    password: root
  #    password: GNSpby97452
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  thymeleaf:
    cache: false
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2KB
      max-file-size: 200MB
      max-request-size: 215MB